"""
Django settings for my_ecommerce_project project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import os # Assurez-vous que cette ligne est en haut du fichier si elle n'y est pas

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) # Ligne déjà présente

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# my_ecommerce_project/settings.py

# ...
CSRF_COOKIE_SECURE = False  # COMMENTEZ OU METTEZ À False EN DÉVELOPPEMENT LOCAL
SESSION_COOKIE_SECURE = False # COMMENTEZ OU METTEZ À False EN DÉVELOPPEMENT LOCAL
# ...
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s_1np7001n*lsl-4-k!%0q3-n+le@g73(#xk549jy13ay6qo9v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost'] 


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Crispy Forms
    'crispy_forms',         # <--- Ajoutez cette ligne
    'crispy_bootstrap5',    # <--- Ajoutez cette ligne (après crispy_forms)

    # Vos applications personnalisées
    'accounts',
    'products',
    'cart',
    'orders',
    'vendors',
    'reviews',
]

# ... (vos autres configurations comme MIDDLEWARE, TEMPLATES, etc.) ...

# Configuration pour Django Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5" # <--- Ajoutez cette ligne
CRISPY_TEMPLATE_PACK = "bootstrap5"   

# Configuration de l'utilisateur personnalisé
AUTH_USER_MODEL = 'accounts.CustomUser' # Indique à Django d'utiliser votre modèle d'utilisateur personnalisé

# Configuration des fichiers médias (pour les images de produits, logos de vendeurs, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media' # Crée un dossier 'media' à la racine de votre projet

# Permettre à Django de servir les fichiers médias en développement
# Ceci est pour le développement uniquement, pour la production, utilisez un serveur web (Nginx/Apache)
# Ne le mettez pas dans settings.py, ajoutez-le à votre urls.py de projet
# from django.conf import settings
# from django.conf.urls.static import static
# urlpatterns = [
#     # ... vos urls
# ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# ... (Gardez le reste de votre fichier settings.py)
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', # <--- DOIT ÊTRE ICI !
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # ... (vos autres middlewares personnalisés, s'il y en a) ...
]

ROOT_URLCONF = 'my_ecommerce_project.urls'

# my_ecommerce_project/settings.py

# ... (autres imports) ...

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Ajout du processeur de contexte pour le panier
                'my_ecommerce_project.context_processors.cart_total_quantity', 
                # 'my_ecommerce_project.context_processors.categories_context', # Si vous avez un autre processeur
            ],
        },
    },
]

# ... (reste de votre settings.py) ...


WSGI_APPLICATION = 'my_ecommerce_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr-FR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

import os

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, '/static'), # Ou l'endroit où se trouve votre dossier static principal
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Où collectstatic va rassembler les fichiers

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# my_ecommerce_project/settings.py
# ...
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend' # Pour le développement (affiche les emails dans la console)
# Ou pour la production :
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'votre_serveur_smtp.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'yaliouagmoussa@gmail.com'
EMAIL_HOST_PASSWORD = 'yt6201@&'
DEFAULT_FROM_EMAIL = 'yaliouagmoussa@gmail.com' # L'adresse d'envoi par défaut
# ...


# my_ecommerce_project/settings.py
LOGIN_URL = '/accounts/login/' # L'URL de votre page de connexion
LOGIN_REDIRECT_URL = 'vendors:vendor_dashboard' # Si vous voulez que les vendeurs soient redirigés ici après connexion
 # L'URL vers laquelle rediriger après une connexion réussie (ex: page d'accueil)
LOGOUT_REDIRECT_URL = 'home'    # L'URL vers laquelle rediriger après une déconnexion réussie


CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000',
    # Ajoutez d'autres origines si nécessaire, par exemple 'https://*.votre-domaine.com'
]