# Generated by Django 5.2.1 on 2025-05-20 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(help_text="Un identifiant unique pour l'URL de la catégorie (ex: robes-ete)", unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description de la catégorie')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Catégorie parente')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom du produit')),
                ('slug', models.SlugField(help_text="Un identifiant unique pour l'URL du produit", unique=True)),
                ('description', models.TextField(verbose_name='Description détaillée du produit')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix de base')),
                ('material', models.CharField(blank=True, choices=[('cotton', 'Coton'), ('polyester', 'Polyester'), ('silk', 'Soie'), ('wool', 'Laine'), ('denim', 'Denim'), ('leather', 'Cuir'), ('linen', 'Lin'), ('rayon', 'Rayonne'), ('spandex', 'Spandex'), ('blend', 'Mélange'), ('other', 'Autre')], max_length=50, verbose_name='Matière principale')),
                ('condition', models.CharField(choices=[('new', 'Neuf avec étiquette'), ('likenew', 'Comme neuf (porté une ou deux fois)'), ('good', "Bon état (quelques signes d'usure)"), ('fair', 'État correct (usure visible)'), ('vintage', 'Vintage')], default='new', max_length=10, verbose_name='État du produit')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de validation'), ('active', 'Actif'), ('archived', 'Archivé'), ('out_of_stock', 'En rupture de stock')], default='draft', max_length=15, verbose_name='Statut du produit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Catégorie')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.vendor', verbose_name='Vendeur')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Fichier image')),
                ('is_main', models.BooleanField(default=False, verbose_name='Image principale')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Image de Produit',
                'verbose_name_plural': 'Images de Produits',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='Taille')),
                ('color', models.CharField(max_length=50, verbose_name='Couleur')),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Laissez vide si le prix est le même que celui du produit de base.', max_digits=10, null=True)),
                ('stock', models.IntegerField(default=0, verbose_name='Stock disponible')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='SKU (Stock Keeping Unit)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Variante de Produit',
                'verbose_name_plural': 'Variantes de Produit',
                'ordering': ['product', 'size', 'color'],
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
