# Generated by Django 5.2.1 on 2025-05-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productimage_options_category_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['tree_id', 'lft'], 'verbose_name': 'Catégorie', 'verbose_name_plural': 'Catégories'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product', 'size', 'color'], 'verbose_name': 'Variante de Produit', 'verbose_name_plural': 'Variantes de Produits'},
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Taille'),
        ),
    ]
